# Generated by Django 5.2.1 on 2025-06-03 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('resume_type', models.CharField(choices=[('GENERAL', 'General Purpose'), ('TECH', 'Technical'), ('EXECUTIVE', 'Executive'), ('CREATIVE', 'Creative'), ('ACADEMIC', 'Academic'), ('ENTRY', 'Entry Level'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('file', models.FileField(upload_to='resumes/')),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_job_titles', models.CharField(blank=True, max_length=200)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
