# Generated by Django 5.2.1 on 2025-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_type',
            field=models.CharField(choices=[('GENERAL', 'General Purpose'), ('PYTHON', 'Python Developer'), ('REACT', 'React Developer'), ('FULLSTACK', 'Full Stack Developer'), ('DATA', 'Data Analyst'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
    ]
